In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
x=np.array([5,15,25,35,45,55]).reshape((-1,1))
y=np.array([15,11,2,8,25,32])
transformer=PolynomialFeatures(degree=2,include_bias=False)
transformer.fit(x)
xn=transformer.transform(x)
xn=PolynomialFeatures(degree=2,include_bias=False).fit_transform(x)
xn

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [3]:
model=LinearRegression().fit(xn,y)
r_sq=model.score(xn,y)
print("coefficient of determination:",r_sq)
print("intercept:",model.intercept_)
print("coefficients:",model.coef_)

coefficient of determination: 0.8908516262498565
intercept: 21.372321428571425
coefficients: [-1.32357143  0.02839286]


In [4]:
xn=PolynomialFeatures(degree=2,include_bias=True).fit_transform(x)
xn

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [5]:
model=LinearRegression(fit_intercept=False).fit(xn,y)
yp=model.predict(xn)
print(yp)

[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
