In [1]:
import numpy as np
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [2]:
a.shape

(20,)

In [3]:
a[4]

4

In [4]:
a=np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [5]:
x=np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [6]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [7]:
y=np.empty(9)
y

array([4.67296746e-307, 1.69121096e-306, 1.86921143e-306, 1.89146896e-307,
       7.56571288e-307, 3.11525958e-307, 1.24610723e-306, 1.29061142e-306,
       5.53353523e-322])

In [8]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [9]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
np.linspace(3,6,7)

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ])

In [12]:
a=np.array(22)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(b)
print(c)
print(d)

22
[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
