In [39]:
import numpy as np
from sklearn.model_selection import train_test_split
x=np.arange(1,25).reshape(12,2)
y=np.array([0,1,1,0,1,0,0,1,1,0,1,0])
print(x)
print(y)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
[0 1 1 0 1 0 0 1 1 0 1 0]


In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y)
print(x_train)

[[ 9 10]
 [19 20]
 [23 24]
 [ 5  6]
 [11 12]
 [ 7  8]
 [13 14]
 [17 18]
 [21 22]]


In [41]:
print(x_test)

[[ 3  4]
 [ 1  2]
 [15 16]]


In [42]:
print(y_train)
print(y_test)

[1 0 0 1 0 0 0 1 1]
[1 0 1]


In [43]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=4,random_state=4,shuffle=False)

In [44]:
print(x_train)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [45]:
print(x_test)

[[17 18]
 [19 20]
 [21 22]
 [23 24]]


In [46]:
print(y_train)
print(y_test)

[0 1 1 0 1 0 0 1]
[1 0 1 0]
